version: "3"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: --label-enable --cleanup --interval 300
    labels:
      - com.centurylinklabs.watchtower.enable=true
    network_mode: none
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
