version: "3"

services:
  jellyfin:
    image: jellyfin/jellyfin:10.5.5
    container_name: jellyfin
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=PathPrefix(`/jellyfin`)
      - traefik.http.routers.jellyfin.tls=true
      # no longer required if jellyfin baseurl is set
      # - traefik.http.middlewares.jellyfin.stripprefix.prefixes=/jellyfin
      # - traefik.http.routers.jellyfin.middlewares=jellyfin
    ports:
      # for some reason jellyfin app doesn't work with traefik proxy, open port directly for local mobile clients
      - 8096:8096
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /media/8tb:/media:ro
    networks:
      - web

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=PathPrefix(`/portainer`)
      - traefik.http.routers.portainer.tls=true
      - traefik.http.middlewares.portainer.stripprefix.prefixes=/portainer
      - traefik.http.routers.portainer.middlewares=portainer
    networks:
      - web

volumes:
  jellyfin-config:
  jellyfin-cache:
  portainer-data:

networks:
  web:
    external: true
